:stylesheet: adoc-colony.css

= Query Extract REST API Guide
정진덕;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 오류에 대한 정보가 담겨있다.

| `401 Unauthorized`
| 클라이언트 오류 상태 응답 코드는 해당 리소스에 유효한 인증 자격 증명이 없기 때문에 요청이 적용되지 않았음을 나타냅니다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 메시지 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

operation::overview-errors[snippets='response-fields,links']


예를 들어, 잘못된 요청으로 이벤트를 만들려고 했을 때 다음과 같은 `400 Bad Request` 응답을 받는다.

operation::overview-errors[snippets='http-response']

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어를 사용하며, 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하고, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.


[[resources-index-access]]
=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::index[snippets='curl-request,http-response,links']

[[resources-query]]
== Query

Query 결과를 조회하거나 추출할 때 사용한다.

[[resources-query-extract]]
=== Query 결과 추출

`POST` 요청을 사용하여 Query 결과를 파일로 추출할 수 있다.

operation::query-extract[snippets='curl-request,request-fields,http-response,response-fields,links']

[[resources-query-paging]]
=== Query Paging 조회

`GET` 요청을 사용하여 Query 결과를 Page별로 Http Response로 조회할 수 있다.

operation::query-paging[snippets='curl-request,request-parameters,request-fields,http-response,response-fields,links']

[[resources-table]]
== 테이블

테이블의 데이터를 보거나, 추출할 수 있다.

[[resources-table-samples]]
=== 테이블 샘플 조회

`Get` 요청을 사용해서 테이블을 Page별로 Http Response로 조회할 수 있다.

operation::table-samples[snippets='curl-request,request-fields,http-response,response-fields,links']

[[resources-table-paging]]
=== 테이블 Paging 조회

`Get` 요청을 사용해서 테이블 Sample Http Response로 조회할 수 있다.

operation::table-paging[snippets='curl-request,request-parameters,request-fields,http-response,response-fields,links']

[[resources-table-extract]]
=== 테이블 추출

`Post` 요청을 사용해서 테이블을 추출할 수 있다.

operation::table-extract[snippets='curl-request,request-fields,http-response,response-fields,links']
